config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  # Health check should be first
  get "up" => "rails/health#show", as: :rails_health_check

  # Devise routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Wrap the custom 2FA route in devise_scope
  devise_scope :user do
    get 'users/two_factor', to: 'users/sessions#two_factor', as: :two_factor
  end

  resources :account_connections, only: [:destroy]

  # Admin routes - MUST come before wildcard routes
  namespace :admin do
    get "inbox/index"

    mount Sidekiq::Web => "/sidekiq"

    namespace :website do
      get "/", to: "website#index", as: "websites"
      get "/:id/preview", to: "website#show", as: "website_show"
      get "/:id/edit", to: "website#edit", as: "website_edit"
      get "/new", to: "website#new", as: "website_new"
      get "/reports", to: "website#reports", as: "website_reports"

      get "/services/", to: "services#view_all", as: "all_website_services"
      get "/:id/services/", to: "services#index", as: "website_services"
      get "/:id/services/:service_id/edit", to: "services#edit", as: "edit_website_service"
      get "/services/new", to: "services#new", as: "new_website_service"
      get "/services/reports", to: "services#reports", as: "website_services_reports"

      get "/blogs/", to: "blogs#view_all", as: "all_website_blogs"
      get "/:id/blogs/", to: "blogs#index", as: "website_blogs"
      get "/:id/blogs/:blog_id/edit", to: "blogs#edit", as: "edit_website_blog"
      get "/blogs/new", to: "blogs#new", as: "new_website_blog"
      get "/blogs/reports", to: "blogs#reports", as: "website_blogs_reports"

      get "/products/", to: "products#view_all", as: "all_website_products"
      get "/:id/products/", to: "products#index", as: "website_products"
      get "/:id/products/:product_id/edit", to: "products#edit", as: "edit_website_product"
      get "/products/new", to: "products#new", as: "new_website_product"
      get "/products/reports", to: "products#reports", as: "website_products_reports"
    end

    get "/", to: "dashboard#index", as: "dashboard"

    # Media
    resources :media, only: [:index, :create]

    # Components
    get "/components", to: 'components#index', as: 'components'
    get "/components/:id/preview", to: 'components#preview', as: 'component_preview'
    get "/components/new", to: 'components#new', as: 'components_new'
    get "/components/:id", to: 'components#show', as: 'components_show'
    get "/components/:id/edit", to: 'components#edit', as: 'components_edit'
    post "/components", to: 'components#create'
    patch "/components/:id", to: 'components#update'
    put "/components/:id", to: 'components#update'
    delete "/components/:id", to: 'components#destroy'

    # Theme pages routes
    get "/themes/:id/pages/new", to: 'themes#add_page', as: 'add_page'
    post "/themes/:id/pages", to: 'themes#create_pages', as: 'create_pages'
    get "/themes/:id/css", to: 'themes#theme_css', as: 'theme_css'
    post "/themes/:id/css/save", to: 'themes#theme_css_save', as: 'theme_css_save'

    get "/themes/:id/page/:theme_page_id", to: 'theme_pages#index', as: 'theme_page'
    get "/themes/:id/page/:theme_page_id/preview", to: 'theme_pages#preview', as: 'theme_page_preview'
    get "/themes/:id/page/:theme_page_id/inner-page", to: 'theme_pages#inner_page', as: 'theme_page_inner_page'
    patch "themes/:id/theme-page/:theme_page_id/add", to: 'theme_pages#add_component', as: 'theme_pages_add_component'
    delete "/themes/:id/theme-pages/:theme_page_id/remove", to: 'theme_pages#remove_component', as: 'theme_pages_remove_component'
    patch "/themes/:id/theme-pages/:theme_page_id/reorder_components", to: 'theme_pages#reorder_components', as: 'theme_pages_reorder_components'

    patch "themes/:id/theme-page/:theme_page_id/inner-page/add", to: 'theme_pages#inner_add_component', as: 'theme_inner_pages_add_component'
    delete "/themes/:id/theme-pages/:theme_page_id/inner-page/remove", to: 'theme_pages#inner_remove_component', as: 'theme_inner_pages_remove_component'
    patch "/themes/:id/theme-pages/:theme_page_id/inner-page/reorder_components", to: 'theme_pages#inner_reorder_components', as: 'theme_inner_pages_reorder_components'

    # Notifications routes
    get "/notifications", to: 'notifications#index', as: 'notifications'
    get "/notifications/:id", to: 'notifications#show', as: 'notification'
    post "/notifications/:id/read", to: 'notifications#read', as: 'notification_read'

    # Users routes
    get "/users", to: "users#index", as: 'users'
    get "/users/new", to: "users#new", as: "new_user"
    post "/users", to: "users#create"
    get "/users/reports", to: 'users#reports', as: 'user_reports'
    get "/users/:id", to: "users#show", as: "user"
    get "/users/:id/edit", to: "users#edit", as: "edit_user"
    patch "/users/:id", to: "users#update"
    put "/users/:id", to: "users#update"
    delete "/users/:id", to: "users#destroy"
    get "/users/:id/edit_password", to: "users#edit_password", as: "edit_password"
    patch "/users/:id/update_password", to: "users#update_password", as: "update_password"

    get "/users/:id/setup", to: "users#setup_user", as: "user_setup"
    patch "/users/:id/update_setup", to: "users#update_setup", as: "update_setup"

    resources :themes
    get '/themes/:id/settings', to: 'themes#settings', as: 'themes_settings'
    patch '/themes/:id/settings', to: 'themes#update_settings', as: 'themes_update_settings'

    # Index - List all help articles
    get "/help-articles", to: 'help_articles#index', as: 'help_articles'
    get "/help-articles/new", to: 'help_articles#new', as: 'new_help_article'
    post "/help-articles", to: 'help_articles#create'
    get "/help-articles/:id", to: 'help_articles#show', as: 'help_article'
    get "/help-articles/:id/edit", to: 'help_articles#edit', as: 'edit_help_article'
    patch "/help-articles/:id", to: 'help_articles#update'
    put "/help-articles/:id", to: 'help_articles#update'
    delete "/help-articles/:id", to: 'help_articles#destroy'

    get "/page-templates", to: 'page_templates#index', as: 'page_templates'
    get "/page-templates/new", to: 'page_templates#new', as: 'new_page_template'
    post "/page-templates", to: 'page_templates#create'
    get "/page-templates/:id", to: 'page_templates#show', as: 'page_template'
    get "/page-templates/:id/edit", to: 'page_templates#edit', as: 'edit_page_template'
    patch "/page-templates/:id", to: 'page_templates#update'
    put "/page-templates/:id", to: 'page_templates#update'
    delete "/page-templates/:id", to: 'page_templates#destroy'
    patch "/page-templates/:id/add", to: 'page_templates#add_component', as: 'page_template_add_component'
    delete "/page-templates/:id/remove", to: 'page_templates#remove_component', as: 'page_template_remove_component'

    patch "page_templates/:id/reorder_components", to: 'page_templates#reorder_components', as: 'page_template_reorder_components'

    # Inbox Routes
    get "inbox", to: "inbox#index", as: "inbox"
    post "inbox/get_message", to: "inbox#get_message", as: "inbox_get_message"
    post "inbox/get_new_chat", to: "inbox#get_new_chat", as: "inbox_get_new_chat"
    post "inbox/new_chat_message", to: "inbox#new_chat_message", as: "inbox_new_chat_message"
    post "inbox/old_chat_message", to: "inbox#old_chat_message", as: "inbox_old_chat_message"


  end

  # Manage routes - MUST come before wildcard routes
  namespace :manage do

    post "/search-form", to: 'base#search', as: 'search_form'
    post '/help_search', to: 'base#manage_help_search', as: 'help_search'


    namespace :website do
      namespace :editor do

        post '/pages-reorder', to: 'website_editor#update_positions'

        get "/", to: "website_editor#index", as: "website_editor"
        get "/:page_slug", to: "website_editor#show", as: "website_editor_page"
        get "/:page_slug/:inner_page_slug", to: "website_editor#inner_page", as: "website_editor_inner_page"

        post "/sidebar_data", to: "website_editor#sidebar_data", as: "website_editor_sidebar_data"
        post "/single_field_data", to: "website_editor#single_field_data", as: "website_editor_single_field_data"
        post "/page_type", to: "website_editor#page_type", as: "website_editor_page_type"
        post "/add_page_template", to: "website_editor#add_page_template", as: "website_editor_add_page_template"
        post "/show_in_menu", to: "website_editor#show_in_menu", as: "website_editor_show_in_menu"
        post "/delete_from_menu", to: "website_editor#delete_from_menu", as: "website_editor_delete_from_menu"
        post "/duplicate_in_menu", to: "website_editor#duplicate_in_menu", as: "website_editor_duplicate_in_menu"
        post "/rename_page", to: "website_editor#rename_page", as: "website_editor_rename_page"


        post '/sidebar_editor_fields_data', to: "website_editor#sidebar_editor_fields_data", as: "website_editor_sidebar_editor_fields_data"
        post '/sidebar_editor_fields_save', to: "website_editor#sidebar_editor_fields_save", as: "website_editor_sidebar_editor_fields_save"
        post '/add_section', to: "website_editor#add_section", as: "website_editor_add_section"
        post '/add_section_above', to: "website_editor#add_section_above", as: "website_editor_add_section_above"
        post '/remove_section', to: "website_editor#remove_section", as: "website_editor_remove_section"
        post '/reorder_components', to: "website_editor#reorder_components", as: "website_editor_reorder_components"

        patch 'update_colour_scheme', to: 'website_editor#update_colour_scheme'
        patch 'update_font_scheme', to: 'website_editor#update_font_scheme'
        patch 'update_background_scheme', to: 'website_editor#update_background_scheme'


      end

app/models/help_article.rb
class HelpArticle < ApplicationRecord

  belongs_to :user

  scope :search_by_keywords, ->(query) {
    return none if query.blank?

    search_terms = query.downcase.split(/\s+/).select { |term| term.length >= 3 }
    return none if search_terms.empty?

    # More strict: require ALL search terms to match
    results = all

    search_terms.each do |term|
      sanitized_term = "%#{term}%"
      results = results.where(
        "LOWER(title) LIKE ? OR LOWER(text) LIKE ? OR LOWER(keywords::text) LIKE ?",
        sanitized_term, sanitized_term, sanitized_term
      )
    end

    results.order(priority: :desc)
  }

  # Get first 25 words of text
  def excerpt(word_count = 20)
    return '' if text.blank?
    words = text.split(/\s+/)
    excerpt_text = words.first(word_count).join(' ')
    excerpt_text += '...' if words.length > word_count
    excerpt_text
  end

  # Calculate read time (assuming 200 words per minute)
  def read_time
    return 1 if text.blank?
    word_count = text.split(/\s+/).length
    minutes = (word_count / 200.0).ceil
    minutes < 1 ? 1 : minutes
  end
end

app/controllers/admin/help_articles_controller.rb
# app/controllers/admin/help_articles_controller.rb
class Admin::HelpArticlesController < Admin::BaseController
  before_action :set_help_article, only: [:show, :edit, :update, :destroy]

  def index
    @help_articles = HelpArticle.all.order(priority: :desc, created_at: :desc)
  end

  def show
  end

  def new
    @help_article = HelpArticle.new
  end

  def create
    @help_article = HelpArticle.new(help_article_params)
    @help_article.user = current_user

    # Convert comma-separated keywords to array
    if params[:help_article][:keywords_input].present?
      @help_article.keywords = params[:help_article][:keywords_input].split(',').map(&:strip).reject(&:blank?)
    end

    if @help_article.save
      redirect_to [:admin, @help_article], notice: 'Help article was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @help_article.update(help_article_params)
      redirect_to [:admin, @help_article], notice: 'Help article was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @help_article.destroy
    redirect_to admin_help_articles_url, notice: 'Help article was successfully deleted.'
  end

  private

  def set_help_article
    @help_article = HelpArticle.find(params[:id])
  end

  def help_article_params
    params.require(:help_article).permit(:title, :text, :priority, images: [])
  end
end

app/helpers/admin/help_articles_helper.rb
module Admin::HelpArticlesHelper
end

app/views/admin/help_articles/edit.html.erb
<%# app/views/admin/help_articles/edit.html.erb %>
<div class="">
  <div class="mb-8">
    <div class="flex items-center gap-x-3 mb-2">
      <%= link_to admin_help_articles_path, class: "text-gray-400 hover:text-gray-500" do %>
        <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd"/>
        </svg>
      <% end %>
      <h1 class="nata-sans page-title">Edit Help Article</h1>
    </div>
    <p class="nata-sans text-base text-gray-600">Update the details of this help article.</p>
  </div>

  <div class="bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
    <div class="px-4 py-6 sm:p-8">
      <%= render "form", help_article: @help_article %>
    </div>
  </div>
</div>

app/views/admin/help_articles/index.html.erb
<%# app/views/admin/help_articles/index.html.erb %>
<div class="">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="nata-sans page-title">Help Articles</h1>
      <p class="nata-sans font-normal text-base">A list of all help articles including their title, priority, author, and creation date.</p>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <%= link_to "Add Help Article", admin_new_help_article_path, class: "nata-sans inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
    </div>
  </div>

  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="nata-sans py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Title</th>
              <th scope="col" class="nata-sans px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Priority</th>
              <th scope="col" class="nata-sans px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Author</th>
              <th scope="col" class="nata-sans px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Images</th>
              <th scope="col" class="nata-sans px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Created</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Actions</span>
              </th>
            </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
            <% @help_articles.each do |article| %>
              <tr class="hover:bg-gray-50">
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                  <div class="flex items-center">
                    <div class="h-10 w-10 flex-shrink-0">
                      <div class="h-10 w-10 rounded-full bg-indigo-500 flex items-center justify-center">
                        <svg class="h-5 w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                        </svg>
                      </div>
                    </div>
                    <div class="ml-4">
                      <div class="text-sm font-medium text-gray-900 nata-sans"><%= article.title %></div>
                    </div>
                  </div>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                    <span class="nata-sans inline-flex rounded-full px-2 text-xs font-semibold leading-5
                    <%= (article.priority || 0) > 5 ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800' %>">
                      <%= article.priority || 0 %>
                    </span>
                </td>
                <td class="nata-sans whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <%= article.user&.email || 'N/A' %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <span class="nata-sans inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-gray-100 text-gray-800">
                        No images
                      </span>
                </td>
                <td class="nata-sans whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <%= article.created_at.strftime("%b %d, %Y") %>
                </td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <%= link_to "View", admin_help_article_path(article), class: "nata-sans text-indigo-600 hover:text-indigo-900 mr-3" %>
                  <%= link_to "Edit", admin_edit_help_article_path(article), class: "nata-sans text-indigo-600 hover:text-indigo-900 mr-3" %>
                  <%= button_to "Delete", admin_help_article_path(article), method: :delete,
                                data: { confirm: "Are you sure you want to delete this help article?" },
                                class: "nata-sans text-red-600 hover:text-red-900 inline" %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <% if @help_articles.empty? %>
    <div class="text-center py-12">
      <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
      </svg>
      <h3 class="mt-2 text-sm font-medium text-gray-900">No help articles</h3>
      <p class="mt-1 text-sm text-gray-500">Get started by creating a new help article.</p>
      <div class="mt-6">
        <%= link_to "Add Help Article", admin_new_help_article_path, class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/help_articles/new.html.erb
<%# app/views/admin/help_articles/new.html.erb %>
<div class="">
  <div class="mb-8">
    <div class="flex items-center gap-x-3 mb-2">
      <%= link_to admin_help_articles_path, class: "text-gray-400 hover:text-gray-500" do %>
        <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd"/>
        </svg>
      <% end %>
      <h1 class="nata-sans page-title">New Help Article</h1>
    </div>
    <p class="nata-sans text-base text-gray-600">Create a new help article for your knowledge base.</p>
  </div>

  <div class="bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
    <div class="px-4 py-6 sm:p-8">
      <%= render "form", help_article: @help_article %>
    </div>
  </div>
</div>

app/views/admin/help_articles/show.html.erb
<%# app/views/admin/help_articles/show.html.erb %>
<div class="max-w-5xl">
  <div class="mb-8">
    <div class="flex items-center justify-between">
      <div class="flex items-center gap-x-3">
        <%= link_to admin_help_articles_path, class: "text-gray-400 hover:text-gray-500" do %>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd"/>
          </svg>
        <% end %>
        <div>
          <h1 class="nata-sans page-title"><%= @help_article.title %></h1>
          <p class="nata-sans text-sm text-gray-500 mt-1">
            Created <%= @help_article.created_at.strftime("%B %d, %Y at %I:%M %p") %>
          </p>
        </div>
      </div>
      <div class="flex items-center gap-x-3">
        <%= link_to "Edit", admin_edit_help_article_path(@help_article), class: "nata-sans inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
        <%= button_to "Delete", admin_help_article_path(@help_article), method: :delete,
                      data: { confirm: "Are you sure you want to delete this help article?" },
                      class: "nata-sans inline-flex items-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500" %>
      </div>
    </div>
  </div>

  <!-- Article Details Card -->
  <div class="bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl mb-6">
    <div class="px-4 py-6 sm:p-8">
      <h2 class="nata-sans text-base font-semibold leading-7 text-gray-900 mb-4">Article Details</h2>
      <dl class="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-4">
        <div class="border-t border-gray-100 pt-4">
          <dt class="nata-sans text-sm font-medium text-gray-500">Priority</dt>
          <dd class="nata-sans mt-1 text-sm text-gray-900">
            <span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium <%= (@help_article.priority || 0) > 5 ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800' %>">
              <%= @help_article.priority || 0 %>
            </span>
          </dd>
        </div>
        <div class="border-t border-gray-100 pt-4">
          <dt class="nata-sans text-sm font-medium text-gray-500">Author</dt>
          <dd class="nata-sans mt-1 text-sm text-gray-900">
            <%= @help_article.user&.email || 'N/A' %>
          </dd>
        </div>
        <div class="border-t border-gray-100 pt-4">
          <dt class="nata-sans text-sm font-medium text-gray-500">Created</dt>
          <dd class="nata-sans mt-1 text-sm text-gray-900">
            <%= @help_article.created_at.strftime("%B %d, %Y at %I:%M %p") %>
          </dd>
        </div>
        <div class="border-t border-gray-100 pt-4">
          <dt class="nata-sans text-sm font-medium text-gray-500">Last Updated</dt>
          <dd class="nata-sans mt-1 text-sm text-gray-900">
            <%= @help_article.updated_at.strftime("%B %d, %Y at %I:%M %p") %>
          </dd>
        </div>
        <% if @help_article.keywords.present? %>
          <div class="border-t border-gray-100 pt-4 sm:col-span-2">
            <dt class="nata-sans text-sm font-medium text-gray-500 mb-2">Keywords</dt>
            <dd class="nata-sans mt-1 flex flex-wrap gap-2">
              <% @help_article.keywords.each do |keyword| %>
                <span class="inline-flex items-center rounded-full bg-blue-100 px-3 py-0.5 text-xs font-medium text-blue-800">
                  <%= keyword %>
                </span>
              <% end %>
            </dd>
          </div>
        <% end %>
      </dl>
    </div>
  </div>

  <!-- Content Card -->
  <div class="bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl mb-6">
    <div class="px-4 py-6 sm:p-8">
      <h2 class="nata-sans text-base font-semibold leading-7 text-gray-900 mb-4">Content</h2>
      <div class="article-content">
        <%= sanitize(@help_article.text, tags: %w[p strong em u ol ul li br h1 h2 h3 h4 h5 h6 a img span div], attributes: %w[href src alt class style data-list contenteditable]) %>
      </div>
    </div>
  </div>

  <style>
      .article-content {
          font-family: inherit;
          font-size: 0.875rem;
          line-height: 1.5;
          color: #374151;
      }

      .article-content p {
          margin-bottom: 1rem !important;
      }

      .article-content strong {
          font-weight: 600 !important;
          color: #111827 !important;
      }

      .article-content em {
          font-style: italic !important;
      }

      .article-content u {
          text-decoration: underline !important;
      }

      .article-content ol {
          list-style-type: decimal !important;
          list-style-position: outside !important;
          margin-left: 1.5rem !important;
          margin-bottom: 1rem !important;
          padding-left: 0.5rem !important;
      }

      .article-content ul {
          list-style-type: disc !important;
          list-style-position: outside !important;
          margin-left: 1.5rem !important;
          margin-bottom: 1rem !important;
          padding-left: 0.5rem !important;
      }

      .article-content li {
          margin-bottom: 0.5rem !important;
          padding-left: 0.5rem !important;
          display: list-item !important;
      }

      .article-content h1 {
          font-size: 1.5rem !important;
          font-weight: 700 !important;
          margin-bottom: 1rem !important;
          margin-top: 1.5rem !important;
      }

      .article-content h2 {
          font-size: 1.25rem !important;
          font-weight: 700 !important;
          margin-bottom: 0.75rem !important;
          margin-top: 1.25rem !important;
      }

      .article-content h3 {
          font-size: 1.125rem !important;
          font-weight: 700 !important;
          margin-bottom: 0.5rem !important;
          margin-top: 1rem !important;
      }

      .article-content h4 {
          font-size: 1rem !important;
          font-weight: 700 !important;
          margin-bottom: 0.5rem !important;
          margin-top: 0.75rem !important;
      }

      .article-content a {
          color: #4f46e5 !important;
          text-decoration: underline !important;
      }

      .article-content a:hover {
          color: #4338ca !important;
      }

      .article-content img {
          max-width: 100% !important;
          height: auto !important;
          border-radius: 0.5rem !important;
          margin: 1rem 0 !important;
      }
  </style>

</div>