config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  # Health check should be first
  get "up" => "rails/health#show", as: :rails_health_check

  # Devise routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Wrap the custom 2FA route in devise_scope
  devise_scope :user do
    get 'users/two_factor', to: 'users/sessions#two_factor', as: :two_factor
  end

  resources :account_connections, only: [:destroy]

  # Admin routes - MUST come before wildcard routes
  namespace :admin do
    get "inbox/index"

    mount Sidekiq::Web => "/sidekiq"

    namespace :website do
      get "/", to: "website#index", as: "websites"
      get "/:id/preview", to: "website#show", as: "website_show"
      get "/:id/edit", to: "website#edit", as: "website_edit"
      get "/new", to: "website#new", as: "website_new"
      get "/reports", to: "website#reports", as: "website_reports"

      get "/services/", to: "services#view_all", as: "all_website_services"
      get "/:id/services/", to: "services#index", as: "website_services"
      get "/:id/services/:service_id/edit", to: "services#edit", as: "edit_website_service"
      get "/services/new", to: "services#new", as: "new_website_service"
      get "/services/reports", to: "services#reports", as: "website_services_reports"

      get "/blogs/", to: "blogs#view_all", as: "all_website_blogs"
      get "/:id/blogs/", to: "blogs#index", as: "website_blogs"
      get "/:id/blogs/:blog_id/edit", to: "blogs#edit", as: "edit_website_blog"
      get "/blogs/new", to: "blogs#new", as: "new_website_blog"
      get "/blogs/reports", to: "blogs#reports", as: "website_blogs_reports"

      get "/products/", to: "products#view_all", as: "all_website_products"
      get "/:id/products/", to: "products#index", as: "website_products"
      get "/:id/products/:product_id/edit", to: "products#edit", as: "edit_website_product"
      get "/products/new", to: "products#new", as: "new_website_product"
      get "/products/reports", to: "products#reports", as: "website_products_reports"
    end

    get "/", to: "dashboard#index", as: "dashboard"

    # Media
    resources :media, only: [:index, :create]

    # Components
    get "/components", to: 'components#index', as: 'components'
    get "/components/:id/preview", to: 'components#preview', as: 'component_preview'
    get "/components/new", to: 'components#new', as: 'components_new'
    get "/components/:id", to: 'components#show', as: 'components_show'
    get "/components/:id/edit", to: 'components#edit', as: 'components_edit'
    post "/components", to: 'components#create'
    patch "/components/:id", to: 'components#update'
    put "/components/:id", to: 'components#update'
    delete "/components/:id", to: 'components#destroy'

    # Theme pages routes
    get "/themes/:id/pages/new", to: 'themes#add_page', as: 'add_page'
    post "/themes/:id/pages", to: 'themes#create_pages', as: 'create_pages'
    get "/themes/:id/css", to: 'themes#theme_css', as: 'theme_css'
    post "/themes/:id/css/save", to: 'themes#theme_css_save', as: 'theme_css_save'

    get "/themes/:id/page/:theme_page_id", to: 'theme_pages#index', as: 'theme_page'
    get "/themes/:id/page/:theme_page_id/preview", to: 'theme_pages#preview', as: 'theme_page_preview'
    get "/themes/:id/page/:theme_page_id/inner-page", to: 'theme_pages#inner_page', as: 'theme_page_inner_page'
    patch "themes/:id/theme-page/:theme_page_id/add", to: 'theme_pages#add_component', as: 'theme_pages_add_component'
    delete "/themes/:id/theme-pages/:theme_page_id/remove", to: 'theme_pages#remove_component', as: 'theme_pages_remove_component'
    patch "/themes/:id/theme-pages/:theme_page_id/reorder_components", to: 'theme_pages#reorder_components', as: 'theme_pages_reorder_components'

    patch "themes/:id/theme-page/:theme_page_id/inner-page/add", to: 'theme_pages#inner_add_component', as: 'theme_inner_pages_add_component'
    delete "/themes/:id/theme-pages/:theme_page_id/inner-page/remove", to: 'theme_pages#inner_remove_component', as: 'theme_inner_pages_remove_component'
    patch "/themes/:id/theme-pages/:theme_page_id/inner-page/reorder_components", to: 'theme_pages#inner_reorder_components', as: 'theme_inner_pages_reorder_components'

    # Notifications routes
    get "/notifications", to: 'notifications#index', as: 'notifications'
    get "/notifications/:id", to: 'notifications#show', as: 'notification'
    post "/notifications/:id/read", to: 'notifications#read', as: 'notification_read'

    # Users routes
    get "/users", to: "users#index", as: 'users'
    get "/users/new", to: "users#new", as: "new_user"
    post "/users", to: "users#create"
    get "/users/reports", to: 'users#reports', as: 'user_reports'
    get "/users/:id", to: "users#show", as: "user"
    get "/users/:id/edit", to: "users#edit", as: "edit_user"
    patch "/users/:id", to: "users#update"
    put "/users/:id", to: "users#update"
    delete "/users/:id", to: "users#destroy"
    get "/users/:id/edit_password", to: "users#edit_password", as: "edit_password"
    patch "/users/:id/update_password", to: "users#update_password", as: "update_password"

    get "/users/:id/setup", to: "users#setup_user", as: "user_setup"
    patch "/users/:id/update_setup", to: "users#update_setup", as: "update_setup"

    resources :themes
    get '/themes/:id/settings', to: 'themes#settings', as: 'themes_settings'
    patch '/themes/:id/settings', to: 'themes#update_settings', as: 'themes_update_settings'

    # Index - List all help articles
    get "/help-articles", to: 'help_articles#index', as: 'help_articles'
    get "/help-articles/new", to: 'help_articles#new', as: 'new_help_article'
    post "/help-articles", to: 'help_articles#create'
    get "/help-articles/:id", to: 'help_articles#show', as: 'help_article'
    get "/help-articles/:id/edit", to: 'help_articles#edit', as: 'edit_help_article'
    patch "/help-articles/:id", to: 'help_articles#update'
    put "/help-articles/:id", to: 'help_articles#update'
    delete "/help-articles/:id", to: 'help_articles#destroy'

    get "/page-templates", to: 'page_templates#index', as: 'page_templates'
    get "/page-templates/new", to: 'page_templates#new', as: 'new_page_template'
    post "/page-templates", to: 'page_templates#create'
    get "/page-templates/:id", to: 'page_templates#show', as: 'page_template'
    get "/page-templates/:id/edit", to: 'page_templates#edit', as: 'edit_page_template'
    patch "/page-templates/:id", to: 'page_templates#update'
    put "/page-templates/:id", to: 'page_templates#update'
    delete "/page-templates/:id", to: 'page_templates#destroy'
    patch "/page-templates/:id/add", to: 'page_templates#add_component', as: 'page_template_add_component'
    delete "/page-templates/:id/remove", to: 'page_templates#remove_component', as: 'page_template_remove_component'

    patch "page_templates/:id/reorder_components", to: 'page_templates#reorder_components', as: 'page_template_reorder_components'

    # Inbox Routes
    get "inbox", to: "inbox#index", as: "inbox"
    post "inbox/get_message", to: "inbox#get_message", as: "inbox_get_message"
    post "inbox/get_new_chat", to: "inbox#get_new_chat", as: "inbox_get_new_chat"
    post "inbox/new_chat_message", to: "inbox#new_chat_message", as: "inbox_new_chat_message"
    post "inbox/old_chat_message", to: "inbox#old_chat_message", as: "inbox_old_chat_message"


  end

  # Manage routes - MUST come before wildcard routes
  namespace :manage do

    post "/search-form", to: 'base#search', as: 'search_form'
    post '/help_search', to: 'base#manage_help_search', as: 'help_search'


    namespace :website do
      namespace :editor do

        post '/pages-reorder', to: 'website_editor#update_positions'

        get "/", to: "website_editor#index", as: "website_editor"
        get "/:page_slug", to: "website_editor#show", as: "website_editor_page"
        get "/:page_slug/:inner_page_slug", to: "website_editor#inner_page", as: "website_editor_inner_page"

        post "/sidebar_data", to: "website_editor#sidebar_data", as: "website_editor_sidebar_data"
        post "/single_field_data", to: "website_editor#single_field_data", as: "website_editor_single_field_data"
        post "/page_type", to: "website_editor#page_type", as: "website_editor_page_type"
        post "/add_page_template", to: "website_editor#add_page_template", as: "website_editor_add_page_template"
        post "/show_in_menu", to: "website_editor#show_in_menu", as: "website_editor_show_in_menu"
        post "/delete_from_menu", to: "website_editor#delete_from_menu", as: "website_editor_delete_from_menu"
        post "/duplicate_in_menu", to: "website_editor#duplicate_in_menu", as: "website_editor_duplicate_in_menu"
        post "/rename_page", to: "website_editor#rename_page", as: "website_editor_rename_page"


        post '/sidebar_editor_fields_data', to: "website_editor#sidebar_editor_fields_data", as: "website_editor_sidebar_editor_fields_data"
        post '/sidebar_editor_fields_save', to: "website_editor#sidebar_editor_fields_save", as: "website_editor_sidebar_editor_fields_save"
        post '/add_section', to: "website_editor#add_section", as: "website_editor_add_section"
        post '/add_section_above', to: "website_editor#add_section_above", as: "website_editor_add_section_above"
        post '/remove_section', to: "website_editor#remove_section", as: "website_editor_remove_section"
        post '/reorder_components', to: "website_editor#reorder_components", as: "website_editor_reorder_components"

        patch 'update_colour_scheme', to: 'website_editor#update_colour_scheme'
        patch 'update_font_scheme', to: 'website_editor#update_font_scheme'
        patch 'update_background_scheme', to: 'website_editor#update_background_scheme'


      end

app/helpers/admin/theme_pages_helper.rb
module Admin::ThemePagesHelper

  def render_theme_preview_content(component, theme_page_id = nil, component_page_id)
    componentHTML = component.content['html']
    updated_content = componentHTML

    unless component.editable_fields == ""
      # Get customisations if user_id and theme_page_id are provided
      field_values = component.editable_fields.to_h

      field_values.each do |field_name, field_value|
        updated_content = updated_content.gsub('{{'+field_name.to_s+'}}', field_value.to_s)
      end
    end

    if updated_content.include?('{{nav_items}}')
      unless component.template_patterns == ""
        nav_items_html = render_theme_navbar_items(component)
        updated_content = updated_content.gsub!('{{nav_items}}', nav_items_html)
      end
    end

    updated_content
  end

  def render_theme_preview_css(component, theme)
    componentCSS = component.content['css']
    updated_css_content = componentCSS

    theme_settings = theme.settings

    theme_settings['Colour Scheme'].to_a.each do |name, value|

      if componentCSS.include? '{{' + name + '}}'
        updated_css_content = updated_css_content.gsub!('{{' + name + '}}', value)
      end

    end




    updated_css_content
  end

  private

  def render_theme_navbar_items(component)
    raw_template = component.template_patterns

    # Extract the HTML template from the malformed JSON manually
    # Look for the pattern between the first \" after "nav_items": and the last \"
    if match = raw_template.match(/"nav_items":\s*"(.+)"\s*}/)
      # Unescape the basic escapes but keep the template placeholders
      nav_template = match[1].gsub('\\"', '"')
    else
      # Fallback to the whole string if pattern doesn't match
      nav_template = raw_template
    end

    pages = {
      "Home" => "#",
      "About Us" => "#",
      "Services" => "#",
      "Contact Us" => "#"
    }

    pages.map do |page_name, page_data|
      pageName = page_name
      pageSlug = page_data

      item_html = nav_template.dup

      # Replace nav_item with page_type
      item_html.gsub!('{{nav_item}}', pageName)

      link = '/manage/website/editor/' + pageSlug

      item_html.gsub!('{{nav_item_link}}', link)
      item_html
    end.join("\n")
  end


end

app/views/admin/theme_pages/_component.html.erb
<!-- Component Partial (_component.html.erb) -->
<%
  # Check if this component is already added to the theme page
  is_added = @themePage['components'].any? { |comp| comp['component_id'].to_s == component.id.to_s || comp[:component_id].to_s == component.id.to_s }
%>

<div class="group p-4 border border-gray-200 rounded-lg hover:border-gray-300 hover:shadow-sm transition-all duration-200" id="component-<%= component.id %>">
  <div class="flex items-center justify-between">
    <div class="flex-1 min-w-0">
      <div class="flex items-center gap-3">
        <h4 class="text-sm font-medium text-gray-900 truncate"><%= component.name %></h4>
        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
          <%= component.component_type %>
        </span>
      </div>
    </div>

    <div class="ml-4 flex-shrink-0">
      <% if is_added %>
        <span class="inline-flex items-center px-3 py-1.5 bg-green-100 text-green-800 text-sm font-medium rounded-md border border-green-200">
          <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
          </svg>
          Added
        </span>
      <% else %>
        <%= button_to "Add Component",
                      admin_theme_pages_add_component_path(
                        id: @theme.id,
                        theme_page_id: @themePage['theme_page_id'],
                        component_id: component.id
                      ),
                      method: :patch,
                      remote: true,
                      class: "inline-flex items-center px-3 py-1.5 bg-indigo-600 text-white text-sm font-medium rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200",
                      data: {
                        disable_with: "Adding...",
                        turbo_method: :patch
                      } %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/theme_pages/_inner_theme_page_component.html.erb
<!-- Theme Page Component Partial (_theme_page_component.html.erb) -->
<% component = Component.find(theme_page_component['component_id']) %>
<div class="group p-4 border border-gray-200 rounded-lg hover:border-gray-300 hover:shadow-sm transition-all duration-200 draggable-component"
     id="theme-page-component-<%= theme_page_component['component_id'] %>"
     draggable="true"
     data-component-id="<%= theme_page_component['component_id'] %>"
     data-position="<%= theme_page_component['position'] || theme_page_component[:position] %>">
  <div class="flex items-center justify-between">
    <div class="flex-1 min-w-0">
      <div class="flex items-center gap-3">
        <div class="flex items-center text-gray-400 cursor-move drag-handle">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </div>
        <h4 class="text-sm font-medium text-gray-900 truncate"><%= component.name %></h4>
        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
          <%= component.component_type %>
        </span>
      </div>
    </div>

    <div class="ml-4 flex items-center gap-2">
      <%= button_to admin_theme_inner_pages_remove_component_path(
                      id: @theme.id,
                      theme_page_id: @themePage['theme_page_id'],
                      component_id: component.id
                    ),
                    method: :delete,
                    remote: true,
                    class: "inline-flex items-center p-1.5 text-red-600 hover:text-red-700 hover:bg-red-50 rounded-md transition-colors duration-200",
                    data: {
                      confirm: "Are you sure you want to remove this component?",
                      disable_with: "Removing...",
                      turbo_method: :delete
                    },
                    title: "Remove component" do %>
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
        </svg>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/theme_pages/_theme_page_component.html.erb
<!-- Theme Page Component Partial (_theme_page_component.html.erb) -->
<% component = Component.find(theme_page_component['component_id']) %>
<div class="group p-4 border border-gray-200 rounded-lg hover:border-gray-300 hover:shadow-sm transition-all duration-200 draggable-component"
     id="theme-page-component-<%= theme_page_component['component_id'] %>"
     draggable="true"
     data-component-id="<%= theme_page_component['component_id'] %>"
     data-position="<%= theme_page_component['position'] || theme_page_component[:position] %>">
  <div class="flex items-center justify-between">
    <div class="flex-1 min-w-0">
      <div class="flex items-center gap-3">
        <div class="flex items-center text-gray-400 cursor-move drag-handle">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </div>
        <h4 class="text-sm font-medium text-gray-900 truncate"><%= component.name %></h4>
        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
          <%= component.component_type %>
        </span>
      </div>
    </div>

    <div class="ml-4 flex items-center gap-2">
      <%= button_to admin_theme_pages_remove_component_path(
                      id: @theme.id,
                      theme_page_id: @themePage['theme_page_id'],
                      component_id: component.id
                    ),
                    method: :delete,
                    remote: true,
                    class: "inline-flex items-center p-1.5 text-red-600 hover:text-red-700 hover:bg-red-50 rounded-md transition-colors duration-200",
                    data: {
                      confirm: "Are you sure you want to remove this component?",
                      disable_with: "Removing...",
                      turbo_method: :delete
                    },
                    title: "Remove component" do %>
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
        </svg>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/theme_pages/index.html.erb
<!-- Main Theme Page Layout -->
<div class="">
  <div class="bg-white shadow-sm border border-gray-200 overflow-hidden sm:rounded-lg">
    <div class="px-4 py-5 sm:px-6 flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
      <div class="flex-1">
        <h3 class="text-xl leading-6 font-semibold text-gray-900 capitalize"><%= @theme.name %> - <%= @pageName %></h3>
        <p class="mt-2 max-w-2xl text-sm text-gray-600"><%= @theme.description %></p>
      </div>
      <div class="flex flex-wrap gap-2 sm:gap-3">
        <%= link_to "Edit Theme", edit_admin_theme_path(@theme),
                    class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-lg text-gray-700 bg-white hover:bg-gray-50 hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200" %>
        <%= link_to "Preview", admin_dashboard_path(id: @theme.id, theme_page_id: @themePage['theme_page_id']),
                    class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-lg text-gray-700 bg-white hover:bg-gray-50 hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200" %>
        <%= link_to "Back To Theme", admin_theme_path(id: @theme.id),
                    class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-lg text-gray-700 bg-white hover:bg-gray-50 hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200" %>
      </div>
    </div>
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-6">
    <!-- Available Components -->
    <div class="bg-white shadow-sm border border-gray-200 overflow-hidden sm:rounded-lg">
      <div class="px-5 py-4 border-b border-gray-200">
        <h2 class="text-lg font-semibold text-gray-900">Available Components</h2>
        <p class="mt-1 text-sm text-gray-600">Drag and drop or click to add components</p>
      </div>
      <div class="p-5">
        <div id="available-components" class="space-y-3">
          <% @components.each do |component| %>
            <%= render 'component',
                       component: component %>
          <% end %>
        </div>
      </div>
    </div>

    <!-- Page Components -->
    <div class="bg-white shadow-sm border border-gray-200 overflow-hidden sm:rounded-lg">
      <div class="px-5 py-4 border-b border-gray-200">
        <h2 class="text-lg font-semibold text-gray-900">Page Components</h2>
        <p class="mt-1 text-sm text-gray-600">Components currently on this page</p>
      </div>
      <div class="p-5">
        <div id="page-components" class="space-y-3">
          <% if @themePage['components'].any? %>
            <% @themePage['components'].sort_by { |component| component[:position] || component['position'] || 0 }.each do |theme_page_component| %>
              <%= render 'theme_page_component', theme_page_component: theme_page_component %>
            <% end %>
          <% else %>
            <div id="empty-components-message" class="text-center py-8">
              <div class="w-12 h-12 mx-auto mb-4 text-gray-400">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
                </svg>
              </div>
              <p class="text-gray-500 text-sm">No components added yet.</p>
              <p class="text-gray-400 text-xs mt-1">Add components from the left panel to get started</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- Bottom Navigation -->
  <div class="mt-8 flex justify-between items-center">
    <%= link_to admin_theme_path(id: @theme.id),
                class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-lg text-gray-700 bg-white hover:bg-gray-50 hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200" do %>
      <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
      </svg>
      Back to Theme
    <% end %>

    <div id="component-stats" class="text-sm text-gray-500">
      <%= pluralize(@components.count, 'component') %> available •
      <%= pluralize(@themePage['components'].count, 'component') %> added
    </div>
  </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        let draggedElement = null;
        let placeholder = null;

        document.addEventListener('dragstart', function(e) {
            if (e.target.classList.contains('draggable-component')) {
                draggedElement = e.target;
                e.target.style.opacity = '0.5';
                e.dataTransfer.effectAllowed = 'move';
                e.dataTransfer.setData('text/html', '');

                placeholder = document.createElement('div');
                placeholder.className = 'border-2 border-dashed border-blue-400 rounded-lg p-4 bg-blue-50';
                placeholder.innerHTML = '<div class="text-center text-blue-600 text-sm">Drop here</div>';
                placeholder.style.height = draggedElement.offsetHeight + 'px';
            }
        });

        document.addEventListener('dragend', function(e) {
            if (e.target.classList.contains('draggable-component')) {
                e.target.style.opacity = '';
                if (placeholder && placeholder.parentNode) {
                    placeholder.parentNode.removeChild(placeholder);
                }
                placeholder = null;
                draggedElement = null;
            }
        });

        document.addEventListener('dragover', function(e) {
            const pageComponents = document.getElementById('page-components');
            if (!pageComponents || !draggedElement) return;

            let container = pageComponents.querySelector('.space-y-3');
            if (!container) {
                container = pageComponents;
            }

            if (container.contains(e.target) || e.target === container) {
                e.preventDefault();
                e.dataTransfer.dropEffect = 'move';

                if (placeholder && placeholder.parentNode) {
                    placeholder.parentNode.removeChild(placeholder);
                }

                const afterElement = getElementAfter(container, e.clientY);

                if (afterElement) {
                    container.insertBefore(placeholder, afterElement);
                } else {
                    container.appendChild(placeholder);
                }
            }
        });

        document.addEventListener('drop', function(e) {
            const pageComponents = document.getElementById('page-components');
            if (!pageComponents || !draggedElement || !placeholder) return;

            let container = pageComponents.querySelector('.space-y-3');
            if (!container) {
                container = pageComponents;
            }

            if (container.contains(e.target) || e.target === container) {
                e.preventDefault();

                if (placeholder.parentNode) {
                    placeholder.parentNode.insertBefore(draggedElement, placeholder);
                    placeholder.parentNode.removeChild(placeholder);
                }

                updateComponentPositions();
            }
        });

        document.addEventListener('dragenter', function(e) {
            const pageComponents = document.getElementById('page-components');
            if (pageComponents && (pageComponents.contains(e.target) || e.target === pageComponents)) {
                e.preventDefault();
            }
        });

        function getElementAfter(container, y) {
            const draggableElements = [...container.querySelectorAll('.draggable-component')].filter(child => {
                return child !== draggedElement;
            });

            let closestElement = null;
            let closestDistance = Number.POSITIVE_INFINITY;

            draggableElements.forEach((child) => {
                const box = child.getBoundingClientRect();
                const distance = y - (box.top + box.height / 2);

                if (distance < 0 && Math.abs(distance) < closestDistance) {
                    closestDistance = Math.abs(distance);
                    closestElement = child;
                }
            });

            return closestElement;
        }

        function updateComponentPositions() {
            const pageComponents = document.getElementById('page-components');
            if (!pageComponents) return;

            let container = pageComponents.querySelector('.space-y-3');
            if (!container) {
                container = pageComponents;
            }

            const components = container.querySelectorAll('.draggable-component');
            const positions = [];

            components.forEach((component, index) => {
                const componentId = component.dataset.componentId;
                if (componentId) {
                    positions.push({
                        component_id: componentId,
                        position: index + 1
                    });
                }
            });

            const themeId = '<%= @theme.id %>';
            const themePageId = '<%= @themePage["theme_page_id"] %>';

            fetch(`/admin/themes/${themeId}/theme-pages/${themePageId}/reorder_components`, {
                method: 'PATCH',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-Token': document.querySelector('[name="csrf-token"]').content,
                    'Accept': 'application/json'
                },
                body: JSON.stringify({ positions: positions })
            }).finally(() => {
                draggedElement = null;
            });
        }
    });
</script>