config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  # Health check should be first
  get "up" => "rails/health#show", as: :rails_health_check

  # Devise routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Wrap the custom 2FA route in devise_scope
  devise_scope :user do
    get 'users/two_factor', to: 'users/sessions#two_factor', as: :two_factor
  end

  resources :account_connections, only: [:destroy]

  # Admin routes - MUST come before wildcard routes
  namespace :admin do
    get "inbox/index"

    mount Sidekiq::Web => "/sidekiq"

    namespace :website do
      get "/", to: "website#index", as: "websites"
      get "/:id/preview", to: "website#show", as: "website_show"
      get "/:id/edit", to: "website#edit", as: "website_edit"
      get "/new", to: "website#new", as: "website_new"
      get "/reports", to: "website#reports", as: "website_reports"

      get "/services/", to: "services#view_all", as: "all_website_services"
      get "/:id/services/", to: "services#index", as: "website_services"
      get "/:id/services/:service_id/edit", to: "services#edit", as: "edit_website_service"
      get "/services/new", to: "services#new", as: "new_website_service"
      get "/services/reports", to: "services#reports", as: "website_services_reports"

      get "/blogs/", to: "blogs#view_all", as: "all_website_blogs"
      get "/:id/blogs/", to: "blogs#index", as: "website_blogs"
      get "/:id/blogs/:blog_id/edit", to: "blogs#edit", as: "edit_website_blog"
      get "/blogs/new", to: "blogs#new", as: "new_website_blog"
      get "/blogs/reports", to: "blogs#reports", as: "website_blogs_reports"

      get "/products/", to: "products#view_all", as: "all_website_products"
      get "/:id/products/", to: "products#index", as: "website_products"
      get "/:id/products/:product_id/edit", to: "products#edit", as: "edit_website_product"
      get "/products/new", to: "products#new", as: "new_website_product"
      get "/products/reports", to: "products#reports", as: "website_products_reports"
    end

    get "/", to: "dashboard#index", as: "dashboard"

    # Media
    resources :media, only: [:index, :create]

    # Components
    get "/components", to: 'components#index', as: 'components'
    get "/components/:id/preview", to: 'components#preview', as: 'component_preview'
    get "/components/new", to: 'components#new', as: 'components_new'
    get "/components/:id", to: 'components#show', as: 'components_show'
    get "/components/:id/edit", to: 'components#edit', as: 'components_edit'
    post "/components", to: 'components#create'
    patch "/components/:id", to: 'components#update'
    put "/components/:id", to: 'components#update'
    delete "/components/:id", to: 'components#destroy'

    # Theme pages routes
    get "/themes/:id/pages/new", to: 'themes#add_page', as: 'add_page'
    post "/themes/:id/pages", to: 'themes#create_pages', as: 'create_pages'
    get "/themes/:id/css", to: 'themes#theme_css', as: 'theme_css'
    post "/themes/:id/css/save", to: 'themes#theme_css_save', as: 'theme_css_save'

    get "/themes/:id/page/:theme_page_id", to: 'theme_pages#index', as: 'theme_page'
    get "/themes/:id/page/:theme_page_id/preview", to: 'theme_pages#preview', as: 'theme_page_preview'
    get "/themes/:id/page/:theme_page_id/inner-page", to: 'theme_pages#inner_page', as: 'theme_page_inner_page'
    patch "themes/:id/theme-page/:theme_page_id/add", to: 'theme_pages#add_component', as: 'theme_pages_add_component'
    delete "/themes/:id/theme-pages/:theme_page_id/remove", to: 'theme_pages#remove_component', as: 'theme_pages_remove_component'
    patch "/themes/:id/theme-pages/:theme_page_id/reorder_components", to: 'theme_pages#reorder_components', as: 'theme_pages_reorder_components'

    patch "themes/:id/theme-page/:theme_page_id/inner-page/add", to: 'theme_pages#inner_add_component', as: 'theme_inner_pages_add_component'
    delete "/themes/:id/theme-pages/:theme_page_id/inner-page/remove", to: 'theme_pages#inner_remove_component', as: 'theme_inner_pages_remove_component'
    patch "/themes/:id/theme-pages/:theme_page_id/inner-page/reorder_components", to: 'theme_pages#inner_reorder_components', as: 'theme_inner_pages_reorder_components'

    # Notifications routes
    get "/notifications", to: 'notifications#index', as: 'notifications'
    get "/notifications/:id", to: 'notifications#show', as: 'notification'
    post "/notifications/:id/read", to: 'notifications#read', as: 'notification_read'

    # Users routes
    get "/users", to: "users#index", as: 'users'
    get "/users/new", to: "users#new", as: "new_user"
    post "/users", to: "users#create"
    get "/users/reports", to: 'users#reports', as: 'user_reports'
    get "/users/:id", to: "users#show", as: "user"
    get "/users/:id/edit", to: "users#edit", as: "edit_user"
    patch "/users/:id", to: "users#update"
    put "/users/:id", to: "users#update"
    delete "/users/:id", to: "users#destroy"
    get "/users/:id/edit_password", to: "users#edit_password", as: "edit_password"
    patch "/users/:id/update_password", to: "users#update_password", as: "update_password"

    get "/users/:id/setup", to: "users#setup_user", as: "user_setup"
    patch "/users/:id/update_setup", to: "users#update_setup", as: "update_setup"

    resources :themes
    get '/themes/:id/settings', to: 'themes#settings', as: 'themes_settings'
    patch '/themes/:id/settings', to: 'themes#update_settings', as: 'themes_update_settings'

    # Index - List all help articles
    get "/help-articles", to: 'help_articles#index', as: 'help_articles'
    get "/help-articles/new", to: 'help_articles#new', as: 'new_help_article'
    post "/help-articles", to: 'help_articles#create'
    get "/help-articles/:id", to: 'help_articles#show', as: 'help_article'
    get "/help-articles/:id/edit", to: 'help_articles#edit', as: 'edit_help_article'
    patch "/help-articles/:id", to: 'help_articles#update'
    put "/help-articles/:id", to: 'help_articles#update'
    delete "/help-articles/:id", to: 'help_articles#destroy'

    get "/page-templates", to: 'page_templates#index', as: 'page_templates'
    get "/page-templates/new", to: 'page_templates#new', as: 'new_page_template'
    post "/page-templates", to: 'page_templates#create'
    get "/page-templates/:id", to: 'page_templates#show', as: 'page_template'
    get "/page-templates/:id/edit", to: 'page_templates#edit', as: 'edit_page_template'
    patch "/page-templates/:id", to: 'page_templates#update'
    put "/page-templates/:id", to: 'page_templates#update'
    delete "/page-templates/:id", to: 'page_templates#destroy'
    patch "/page-templates/:id/add", to: 'page_templates#add_component', as: 'page_template_add_component'
    delete "/page-templates/:id/remove", to: 'page_templates#remove_component', as: 'page_template_remove_component'

    patch "page_templates/:id/reorder_components", to: 'page_templates#reorder_components', as: 'page_template_reorder_components'

    # Inbox Routes
    get "inbox", to: "inbox#index", as: "inbox"
    post "inbox/get_message", to: "inbox#get_message", as: "inbox_get_message"
    post "inbox/get_new_chat", to: "inbox#get_new_chat", as: "inbox_get_new_chat"
    post "inbox/new_chat_message", to: "inbox#new_chat_message", as: "inbox_new_chat_message"
    post "inbox/old_chat_message", to: "inbox#old_chat_message", as: "inbox_old_chat_message"


  end

  # Manage routes - MUST come before wildcard routes
  namespace :manage do

    post "/search-form", to: 'base#search', as: 'search_form'
    post '/help_search', to: 'base#manage_help_search', as: 'help_search'


    namespace :website do
      namespace :editor do

        post '/pages-reorder', to: 'website_editor#update_positions'

        get "/", to: "website_editor#index", as: "website_editor"
        get "/:page_slug", to: "website_editor#show", as: "website_editor_page"
        get "/:page_slug/:inner_page_slug", to: "website_editor#inner_page", as: "website_editor_inner_page"

        post "/sidebar_data", to: "website_editor#sidebar_data", as: "website_editor_sidebar_data"
        post "/single_field_data", to: "website_editor#single_field_data", as: "website_editor_single_field_data"
        post "/page_type", to: "website_editor#page_type", as: "website_editor_page_type"
        post "/add_page_template", to: "website_editor#add_page_template", as: "website_editor_add_page_template"
        post "/show_in_menu", to: "website_editor#show_in_menu", as: "website_editor_show_in_menu"
        post "/delete_from_menu", to: "website_editor#delete_from_menu", as: "website_editor_delete_from_menu"
        post "/duplicate_in_menu", to: "website_editor#duplicate_in_menu", as: "website_editor_duplicate_in_menu"
        post "/rename_page", to: "website_editor#rename_page", as: "website_editor_rename_page"


        post '/sidebar_editor_fields_data', to: "website_editor#sidebar_editor_fields_data", as: "website_editor_sidebar_editor_fields_data"
        post '/sidebar_editor_fields_save', to: "website_editor#sidebar_editor_fields_save", as: "website_editor_sidebar_editor_fields_save"
        post '/add_section', to: "website_editor#add_section", as: "website_editor_add_section"
        post '/add_section_above', to: "website_editor#add_section_above", as: "website_editor_add_section_above"
        post '/remove_section', to: "website_editor#remove_section", as: "website_editor_remove_section"
        post '/reorder_components', to: "website_editor#reorder_components", as: "website_editor_reorder_components"

        patch 'update_colour_scheme', to: 'website_editor#update_colour_scheme'
        patch 'update_font_scheme', to: 'website_editor#update_font_scheme'
        patch 'update_background_scheme', to: 'website_editor#update_background_scheme'


      end

app/controllers/admin/inbox_controller.rb
class Admin::InboxController < Admin::BaseController
  def index
    @chats = InboxChat.all.order(updated_at: :desc)

    # Get last message for each chat
    @chat_data = {}
    @chats.each do |chat|
      last_message = InboxMessage.where(inbox_chat_id: chat.id).order(created_at: :desc).first
      if last_message
        message_text = last_message.message
        preview = message_text.length > 25 ? message_text[0..24] + '...' : message_text
        @chat_data[chat.id] = {
          preview: preview,
          time: last_message.created_at.strftime('%I:%M%p'),
          unread_count: 0 # You can implement unread logic later
        }
      else
        @chat_data[chat.id] = {
          preview: 'No messages yet',
          time: chat.created_at.strftime('%I:%M%p'),
          unread_count: 0
        }
      end
    end
  end

  def get_message
    chat = InboxChat.find(params[:chat_id])
    chatOpenDate = chat.created_at
    chatOpenDateFormat = chatOpenDate.day.ordinalize + ' ' + chatOpenDate.strftime('%B %Y at %I:%M%p')
    messages = InboxMessage.where(inbox_chat_id: chat.id).order(created_at: :asc)

    respond_to do |format|
      format.json do
        render json: {
          html: render_to_string(
            partial: 'admin/inbox/inbox_messages',
            locals: { chat: chat, date: chatOpenDateFormat, messages: messages },
            formats: [:html],
            layout: false
          )
        }
      end
    end
  end

  def get_new_chat
    chatOpenDate = Time.now
    chatOpenDateFormat = chatOpenDate.day.ordinalize + ' ' + chatOpenDate.strftime('%B %Y at %I:%M%p')

    respond_to do |format|
      format.json do
        render json: {
          html: render_to_string(
            partial: 'admin/inbox/new_inbox_message',
            locals: { date: chatOpenDateFormat },
            formats: [:html],
            layout: false
          )
        }
      end
    end
  end

  def new_chat_message
    user = current_user
    @inboxChat = InboxChat.create(user_id: user.id)
    @inboxMessage = InboxMessage.create(
      inbox_chat_id: @inboxChat.id,
      user_id: user.id,
      message: params[:message]
    )

    # Return the updated chat view
    chatOpenDate = @inboxChat.created_at
    chatOpenDateFormat = chatOpenDate.day.ordinalize + ' ' + chatOpenDate.strftime('%B %Y at %I:%M%p')
    messages = InboxMessage.where(inbox_chat_id: @inboxChat.id).order(created_at: :asc)

    # Get the last message preview (25 characters)
    lastMessage = @inboxMessage.message
    lastMessagePreview = lastMessage.length > 25 ? lastMessage[0..24] + '...' : lastMessage

    respond_to do |format|
      format.json do
        render json: {
          html: render_to_string(
            partial: 'admin/inbox/inbox_messages',
            locals: { chat: @inboxChat, date: chatOpenDateFormat, messages: messages },
            formats: [:html],
            layout: false
          ),
          chat_data: {
            id: @inboxChat.id,
            message_preview: lastMessagePreview,
            time: @inboxMessage.created_at.strftime('%I:%M%p'),
            unread_count: 0
          }
        }
      end
    end
  end

  def old_chat_message
    user = current_user
    @inboxChat = InboxChat.find(params[:chat_id])
    @inboxChat.touch # Update the updated_at timestamp

    @inboxMessage = InboxMessage.create(
      inbox_chat_id: @inboxChat.id,
      user_id: user.id,
      message: params[:message]
    )

    # Return the updated chat view
    chatOpenDate = @inboxChat.created_at
    chatOpenDateFormat = chatOpenDate.day.ordinalize + ' ' + chatOpenDate.strftime('%B %Y at %I:%M%p')
    messages = InboxMessage.where(inbox_chat_id: @inboxChat.id).order(created_at: :asc)

    respond_to do |format|
      format.json do
        render json: {
          html: render_to_string(
            partial: 'admin/inbox/inbox_messages',
            locals: { chat: @inboxChat, date: chatOpenDateFormat, messages: messages },
            formats: [:html],
            layout: false
          )
        }
      end
    end
  end
end

app/helpers/admin/inbox_helper.rb
module Admin::InboxHelper
end

app/views/admin/inbox/_inbox_messages.html.erb
<div class="flex items-center justify-between">
  <div class="flex gap-5">
    <div class="">
      <div class="bg-green-500 p-2 rounded-full w-15 h-15">
        <%= image_tag 'single-point-small-white-logo.png', class: '' %>
      </div>
    </div>
    <div>
      <p class="text-lg font-bold nata-sans">SinglePoint Support</p>
      <p class="text-base font-base nata-sans text-gray-500">Support Chat Opened: <%= date %></p>
    </div>
  </div>
  <div>
    <div class="p-2 border rounded-full">
      <svg class="cursor-pointer" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="#000000" id="Dots-Three--Streamline-Phosphor" height="14" width="14">
        <path d="M9.176 8c0 0.9052875 -0.98 1.4710875 -1.764 1.01844375 -0.784 -0.4526375 -0.784 -1.58425 0 -2.0368875 0.17875625 -0.10320625 0.3815875 -0.15755 0.588 -0.15755625 0.64950625 -0.00003125 1.176 0.52649375 1.176 1.176Zm5.488 -1.176c-0.9052875 -0.0000375 -1.47108125 0.97993125 -1.018475 1.76395625 0.4526125 0.78401875 1.58421875 0.78406875 2.03689375 0.0000875 0.10323125 -0.17878125 0.15758125 -0.38159375 0.15758125 -0.58804375 0 -0.64946875 -0.52653125 -1.17596875 -1.176 -1.176Zm-13.328 0c-0.9052875 -0.0000375 -1.47108125 0.97993125 -1.018475 1.76395625 0.4526125 0.78401875 1.58421875 0.78406875 2.03689375 0.0000875 0.10323125 -0.17878125 0.15758125 -0.38159375 0.15758125 -0.58804375 0 -0.64946875 -0.52653125 -1.17596875 -1.176 -1.176Z" stroke-width="0.0625"></path>
      </svg>
    </div>
  </div>
</div>

<div class="bg-white p-3 rounded space-y-4" style="overflow: auto; min-height: calc(100vh - 320px); max-height: calc(100vh - 320px);">
  <% messages.each do |message| %>
    <% is_support = message.user.role == 0 %>
    <div class="flex justify-<%= is_support ? 'end' : 'start' %>">
      <div style="max-width: 60%" class="flex items-end gap-2 <%= is_support ? '' : 'flex-row-reverse' %>">
        <div>
          <div style="border-radius: 10px 10px 0px 10px; padding: 8px 20px;" class="<%= is_support ? 'bg-green-500' : '-ml-5 bg-gray-50' %>">
            <p class="nata-sans text-sm <%= is_support ? 'text-white text-right' : '' %>"><%= message.message %></p>
          </div>
          <div class="mt-1">
            <p class="text-xs nata-sans <%= is_support ? 'text-right' : '' %>">
              <%= message.created_at.strftime('%I:%M%p') %> ~
              <span class="font-semibold"><%= is_support ? 'Support' : message.get_users_name %></span>
            </p>
          </div>
        </div>
        <div>
          <div class="bg-green-500 p-0.5 rounded-full w-3.5 h-3.5">
            <%= image_tag 'single-point-small-white-logo.png', class: '' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flex">
  <form id="old-chat-form" class="flex gap-3 w-full">
    <input type="hidden" name="chat_id" value="<%= chat.id %>">
    <div class="w-full relative">
      <input type="text"
             name="message"
             required
             class="h-11 border rounded w-full py-2 px-3 pr-20 nata-sans text-sm"
             autocomplete="off"
             placeholder="Type a message">
      <div class="w-10 h-10 flex justify-center items-center absolute right-0 top-0.5">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" fill="rgba(107,114,128)" id="Image-Light--Streamline-Phosphor" height="18" width="18">
          <path d="M14.76391875 1.38980625H1.23608125c-0.59430625 0 -1.07608125 0.481775 -1.07608125 1.076075v11.0682375c0 0.5943 0.481775 1.076075 1.07608125 1.076075h13.5278375c0.59430625 0 1.07608125 -0.481775 1.07608125 -1.076075V2.46588125c0 -0.5943 -0.481775 -1.076075 -1.07608125 -1.076075ZM1.23608125 2.31215625h13.5278375c0.0849 0.00000625 0.15373125 0.06883125 0.15373125 0.153725v8.268125L12.6525 8.4688625c-0.42024375 -0.4202875 -1.1016375 -0.4202875 -1.52188125 0l-1.6464 1.6464 -3.4903375 -3.49110625c-0.42024375 -0.4202875 -1.1016375 -0.4202875 -1.52188125 0l-3.38965 3.38965V2.46588125c0 -0.0849 0.068825 -0.15373125 0.15373125 -0.153725Zm-0.15373125 11.2219625v-2.21595625l4.04144375 -4.04144375c0.0601375 -0.060625 0.15815625 -0.060625 0.21829375 0l6.41111875 6.411125H1.23608125c-0.08490625 0 -0.15373125 -0.068825 -0.15373125 -0.153725Zm13.68156875 0.153725h-1.70635l-2.9207875 -2.9207875 1.64563125 -1.6464c0.06005 -0.0601125 0.157475 -0.0601125 0.217525 0l2.92078125 2.9207875v1.492675c0.00001875 0.0861125 -0.0707 0.15544375 -0.1568 0.153725Zm-5.3803875 -7.84c0 -0.5916875 0.64051875 -0.96149375 1.1529375 -0.66565 0.51241875 0.29584375 0.51241875 1.03545625 0 1.3313 -0.11684375 0.0674625 -0.2493875 0.102975 -0.3843125 0.102975 -0.4245 0 -0.768625 -0.344125 -0.768625 -0.768625Z" stroke-width="0.0625"></path>
        </svg>
      </div>
    </div>
    <button type="submit" class="p-2 rounded bg-green-500 w-11 h-11 flex items-center justify-center">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="#fff" id="Paper-Plane-Tilt--Streamline-Phosphor" height="16" width="16">
        <path d="M15.51434375 0.48780625c-0.28676875 -0.28658125 -0.70603125 -0.39581875 -1.0961875 -0.28559375h-0.0105L0.97205 4.27895625C0.14360625 4.5177125 -0.1157125 5.56375 0.50528125 6.161825c0.0860375 0.0828625 0.184775 0.15143125 0.292475 0.2031l5.9443125 2.89515625 2.89095625 5.9408125c0.1836 0.39180625 0.57810625 0.6412375 1.0107875 0.63909375q0.0483 0 0.0966 -0.0042c0.46289375 -0.03748125 0.8537 -0.35878125 0.9799875 -0.8056875l4.0739375 -13.43560625v-0.0105c0.11165 -0.38914375 0.0046 -0.80825 -0.27999375 -1.0961875ZM10.6501125 14.7095l-0.0035 0.0098v-0.0049l-2.80415625 -5.7609125 3.35995 -3.35995c0.29691875 -0.312525 0.14418125 -0.829275 -0.27493125 -0.93015625 -0.1845875 -0.04443125 -0.37911875 0.00769375 -0.51675625 0.1384625l-3.35995625 3.35995625L1.28775 5.3576375h-0.0049l13.42930625 -4.07744375Z" stroke-width="0.0625"></path>
      </svg>
    </button>
  </form>
</div>

app/views/admin/inbox/index.html.erb
<div class="flex gap-5">
  <div class="w-3/10 bg-gray-50 rounded-lg p-4 space-y-5" style="min-height: calc(100vh - 144px); max-height: calc(100vh - 144px); overflow: auto;">
    <div class="flex justify-between items-center">
      <h2 class="nata-sans text-2xl font-bold">Inbox</h2>
      <div onclick="newInboxChat()" class="bg-white rounded-full p-2.5 shadow cursor-pointer">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" fill="#000000" id="Pencil-Line-Light--Streamline-Phosphor" height="15" width="15">
          <path d="m17.4509296875 4.5713953125 -4.0218750000000005 -4.0218750000000005c-0.49203984375 -0.49209609375 -1.2898546875 -0.49209609375 -1.78189453125 0L0.54897890625 11.64679453125c-0.23677734375 0.23596875 -0.36959765625 0.55667109375 -0.36897890625 0.89095078125v4.0218750000000005c0 0.695840625 0.5640890625 1.2599296875000001 1.2599296875000001 1.2599296875000001h15.11914921875c0.41566640624999995 0 0.6754640625 -0.44997890625000003 0.46762734375 -0.8099578125 -0.0964546875 -0.1670625 -0.2747109375 -0.2699859375 -0.46762734375 -0.2699859375H7.063713281249999L17.4509296875 6.353296875c0.49209609375 -0.492046875 0.49209609375 -1.2898617187499999 0 -1.7819015625ZM4.0038890625 14.75971875 11.879346093750002 6.88336171875l1.7567015625 1.7567015625L5.759690625 16.5155203125Zm-0.7640578125 -0.7631578125 -1.7558015624999999 -1.7566945312500002L9.359486718749999 4.364409375l1.7567015625 1.7558015624999999Zm-1.9798875 2.563059375v-3.0166312499999997l3.1966171875000002 3.19662421875H1.4399296874999998c-0.0994078125 0 -0.1799859375 -0.08058515625 -0.1799859375 -0.17999296874999998ZM16.686871875 5.5892390625l-2.28766640625 2.28766640625 -4.2756609375 -4.27655390625 2.28676640625 -2.2867734375000004c0.0703125 -0.07038281249999999 0.18438046875 -0.07038281249999999 0.2546859375 0l4.0218750000000005 4.020975c0.07038281249999999 0.07030546875 0.07038281249999999 0.18438046875 0 0.2546859375Z" stroke-width="0.0703"></path>
        </svg>
      </div>
    </div>
    <div>
      <%= form_with url: manage_search_form_path, method: :post, data: { turbo: false }, id: "quick-search-form" do |form| %>
        <%= form.text_field :search,
                            class: 'border rounded w-full pr-3 py-2 pl-8 nata-sans text-sm',
                            autocomplete: 'off',
                            id: 'quick-search-input',
                            placeholder: 'Search...' %>
      <% end %>
    </div>
    <div>
      <div class="mb-2">
        <p class="nata-sans text-gray-500 text-sm">All Messages</p>
      </div>
      <div class="space-y-4" id="chat-list-container">
        <% @chats.each do |chat| %>
          <% chat_info = @chat_data[chat.id] %>
          <div onclick="adminOpenInboxChat('<%= chat.id %>')" class="flex gap-2 items-center inbox-chat-<%= chat.id %> cursor-pointer">
            <div class="">
              <div class="bg-green-500 p-2 rounded-full w-12 h-12">
                <%= image_tag 'single-point-small-white-logo.png', class: '' %>
              </div>
            </div>
            <div class="w-3/5">
              <p class="text-sm font-bold nata-sans">SinglePoint Support</p>
              <p class="text-xs font-base nata-sans text-gray-500"><%= chat_info[:preview] %></p>
            </div>
            <div class="w-1/5 flex flex-col items-end gap-0.5">
              <p class="text-xs font-base nata-sans text-gray-500 text-right"><%= chat_info[:time] %></p>
              <% if chat_info[:unread_count] > 0 %>
                <div class="w-4 h-4 bg-red-500 rounded-full flex items-center justify-center">
                  <p style="font-size: 0.5rem" class="nata-sans text-white"><%= chat_info[:unread_count] %></p>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
  <div class="w-7/10 bg-gray-50 rounded-lg p-4" style="min-height: calc(100vh - 144px); max-height: calc(100vh - 144px);">
    <div class="inbox-chat-notice">
      <% if @chats.empty? %>
        <p>Create New Chat</p>
      <% else %>
        <p>Click A Chat On the Left To view your chat</p>
      <% end %>
    </div>
    <div class="inbox-chat-area space-y-3">

    </div>
  </div>
</div>