config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  # Health check should be first
  get "up" => "rails/health#show", as: :rails_health_check

  # Devise routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Wrap the custom 2FA route in devise_scope
  devise_scope :user do
    get 'users/two_factor', to: 'users/sessions#two_factor', as: :two_factor
  end

  resources :account_connections, only: [:destroy]

  # Admin routes - MUST come before wildcard routes
  namespace :admin do
    get "inbox/index"

    mount Sidekiq::Web => "/sidekiq"

    namespace :website do
      get "/", to: "website#index", as: "websites"
      get "/:id/preview", to: "website#show", as: "website_show"
      get "/:id/edit", to: "website#edit", as: "website_edit"
      get "/new", to: "website#new", as: "website_new"
      get "/reports", to: "website#reports", as: "website_reports"

      get "/services/", to: "services#view_all", as: "all_website_services"
      get "/:id/services/", to: "services#index", as: "website_services"
      get "/:id/services/:service_id/edit", to: "services#edit", as: "edit_website_service"
      get "/services/new", to: "services#new", as: "new_website_service"
      get "/services/reports", to: "services#reports", as: "website_services_reports"

      get "/blogs/", to: "blogs#view_all", as: "all_website_blogs"
      get "/:id/blogs/", to: "blogs#index", as: "website_blogs"
      get "/:id/blogs/:blog_id/edit", to: "blogs#edit", as: "edit_website_blog"
      get "/blogs/new", to: "blogs#new", as: "new_website_blog"
      get "/blogs/reports", to: "blogs#reports", as: "website_blogs_reports"

      get "/products/", to: "products#view_all", as: "all_website_products"
      get "/:id/products/", to: "products#index", as: "website_products"
      get "/:id/products/:product_id/edit", to: "products#edit", as: "edit_website_product"
      get "/products/new", to: "products#new", as: "new_website_product"
      get "/products/reports", to: "products#reports", as: "website_products_reports"
    end

    get "/", to: "dashboard#index", as: "dashboard"

    # Media
    resources :media, only: [:index, :create]

    # Components
    get "/components", to: 'components#index', as: 'components'
    get "/components/:id/preview", to: 'components#preview', as: 'component_preview'
    get "/components/new", to: 'components#new', as: 'components_new'
    get "/components/:id", to: 'components#show', as: 'components_show'
    get "/components/:id/edit", to: 'components#edit', as: 'components_edit'
    post "/components", to: 'components#create'
    patch "/components/:id", to: 'components#update'
    put "/components/:id", to: 'components#update'
    delete "/components/:id", to: 'components#destroy'

    # Theme pages routes
    get "/themes/:id/pages/new", to: 'themes#add_page', as: 'add_page'
    post "/themes/:id/pages", to: 'themes#create_pages', as: 'create_pages'
    get "/themes/:id/css", to: 'themes#theme_css', as: 'theme_css'
    post "/themes/:id/css/save", to: 'themes#theme_css_save', as: 'theme_css_save'

    get "/themes/:id/page/:theme_page_id", to: 'theme_pages#index', as: 'theme_page'
    get "/themes/:id/page/:theme_page_id/preview", to: 'theme_pages#preview', as: 'theme_page_preview'
    get "/themes/:id/page/:theme_page_id/inner-page", to: 'theme_pages#inner_page', as: 'theme_page_inner_page'
    patch "themes/:id/theme-page/:theme_page_id/add", to: 'theme_pages#add_component', as: 'theme_pages_add_component'
    delete "/themes/:id/theme-pages/:theme_page_id/remove", to: 'theme_pages#remove_component', as: 'theme_pages_remove_component'
    patch "/themes/:id/theme-pages/:theme_page_id/reorder_components", to: 'theme_pages#reorder_components', as: 'theme_pages_reorder_components'

    patch "themes/:id/theme-page/:theme_page_id/inner-page/add", to: 'theme_pages#inner_add_component', as: 'theme_inner_pages_add_component'
    delete "/themes/:id/theme-pages/:theme_page_id/inner-page/remove", to: 'theme_pages#inner_remove_component', as: 'theme_inner_pages_remove_component'
    patch "/themes/:id/theme-pages/:theme_page_id/inner-page/reorder_components", to: 'theme_pages#inner_reorder_components', as: 'theme_inner_pages_reorder_components'

    # Notifications routes
    get "/notifications", to: 'notifications#index', as: 'notifications'
    get "/notifications/:id", to: 'notifications#show', as: 'notification'
    post "/notifications/:id/read", to: 'notifications#read', as: 'notification_read'

    # Users routes
    get "/users", to: "users#index", as: 'users'
    get "/users/new", to: "users#new", as: "new_user"
    post "/users", to: "users#create"
    get "/users/reports", to: 'users#reports', as: 'user_reports'
    get "/users/:id", to: "users#show", as: "user"
    get "/users/:id/edit", to: "users#edit", as: "edit_user"
    patch "/users/:id", to: "users#update"
    put "/users/:id", to: "users#update"
    delete "/users/:id", to: "users#destroy"
    get "/users/:id/edit_password", to: "users#edit_password", as: "edit_password"
    patch "/users/:id/update_password", to: "users#update_password", as: "update_password"

    get "/users/:id/setup", to: "users#setup_user", as: "user_setup"
    patch "/users/:id/update_setup", to: "users#update_setup", as: "update_setup"

    resources :themes
    get '/themes/:id/settings', to: 'themes#settings', as: 'themes_settings'
    patch '/themes/:id/settings', to: 'themes#update_settings', as: 'themes_update_settings'

    # Index - List all help articles
    get "/help-articles", to: 'help_articles#index', as: 'help_articles'
    get "/help-articles/new", to: 'help_articles#new', as: 'new_help_article'
    post "/help-articles", to: 'help_articles#create'
    get "/help-articles/:id", to: 'help_articles#show', as: 'help_article'
    get "/help-articles/:id/edit", to: 'help_articles#edit', as: 'edit_help_article'
    patch "/help-articles/:id", to: 'help_articles#update'
    put "/help-articles/:id", to: 'help_articles#update'
    delete "/help-articles/:id", to: 'help_articles#destroy'

    get "/page-templates", to: 'page_templates#index', as: 'page_templates'
    get "/page-templates/new", to: 'page_templates#new', as: 'new_page_template'
    post "/page-templates", to: 'page_templates#create'
    get "/page-templates/:id", to: 'page_templates#show', as: 'page_template'
    get "/page-templates/:id/edit", to: 'page_templates#edit', as: 'edit_page_template'
    patch "/page-templates/:id", to: 'page_templates#update'
    put "/page-templates/:id", to: 'page_templates#update'
    delete "/page-templates/:id", to: 'page_templates#destroy'
    patch "/page-templates/:id/add", to: 'page_templates#add_component', as: 'page_template_add_component'
    delete "/page-templates/:id/remove", to: 'page_templates#remove_component', as: 'page_template_remove_component'

    patch "page_templates/:id/reorder_components", to: 'page_templates#reorder_components', as: 'page_template_reorder_components'

    # Inbox Routes
    get "inbox", to: "inbox#index", as: "inbox"
    post "inbox/get_message", to: "inbox#get_message", as: "inbox_get_message"
    post "inbox/get_new_chat", to: "inbox#get_new_chat", as: "inbox_get_new_chat"
    post "inbox/new_chat_message", to: "inbox#new_chat_message", as: "inbox_new_chat_message"
    post "inbox/old_chat_message", to: "inbox#old_chat_message", as: "inbox_old_chat_message"


  end

  # Manage routes - MUST come before wildcard routes
  namespace :manage do

    post "/search-form", to: 'base#search', as: 'search_form'
    post '/help_search', to: 'base#manage_help_search', as: 'help_search'


    namespace :website do
      namespace :editor do

        post '/pages-reorder', to: 'website_editor#update_positions'

        get "/", to: "website_editor#index", as: "website_editor"
        get "/:page_slug", to: "website_editor#show", as: "website_editor_page"
        get "/:page_slug/:inner_page_slug", to: "website_editor#inner_page", as: "website_editor_inner_page"

        post "/sidebar_data", to: "website_editor#sidebar_data", as: "website_editor_sidebar_data"
        post "/single_field_data", to: "website_editor#single_field_data", as: "website_editor_single_field_data"
        post "/page_type", to: "website_editor#page_type", as: "website_editor_page_type"
        post "/add_page_template", to: "website_editor#add_page_template", as: "website_editor_add_page_template"
        post "/show_in_menu", to: "website_editor#show_in_menu", as: "website_editor_show_in_menu"
        post "/delete_from_menu", to: "website_editor#delete_from_menu", as: "website_editor_delete_from_menu"
        post "/duplicate_in_menu", to: "website_editor#duplicate_in_menu", as: "website_editor_duplicate_in_menu"
        post "/rename_page", to: "website_editor#rename_page", as: "website_editor_rename_page"


        post '/sidebar_editor_fields_data', to: "website_editor#sidebar_editor_fields_data", as: "website_editor_sidebar_editor_fields_data"
        post '/sidebar_editor_fields_save', to: "website_editor#sidebar_editor_fields_save", as: "website_editor_sidebar_editor_fields_save"
        post '/add_section', to: "website_editor#add_section", as: "website_editor_add_section"
        post '/add_section_above', to: "website_editor#add_section_above", as: "website_editor_add_section_above"
        post '/remove_section', to: "website_editor#remove_section", as: "website_editor_remove_section"
        post '/reorder_components', to: "website_editor#reorder_components", as: "website_editor_reorder_components"

        patch 'update_colour_scheme', to: 'website_editor#update_colour_scheme'
        patch 'update_font_scheme', to: 'website_editor#update_font_scheme'
        patch 'update_background_scheme', to: 'website_editor#update_background_scheme'


      end

app/models/theme.rb
# app/models/theme.rb
class Theme < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :description, presence: true

  # Custom validation for image
  validate :acceptable_image

  def website_count(theme)
    Website.where(theme_id: theme.id).count
  end

  private

  def acceptable_image
    return unless image.attached?

    unless image.blob.byte_size <= 10.megabytes
      errors.add(:image, "is too big (should be less than 10MB)")
    end

    # Added WebP to acceptable types
    acceptable_types = ["image/jpeg", "image/jpg", "image/png", "image/gif", "image/webp"]
    unless acceptable_types.include?(image.blob.content_type)
      errors.add(:image, "must be a JPEG, PNG, GIF, or WebP")
    end
  end



end

app/controllers/admin/themes_controller.rb
class Admin::ThemesController < Admin::BaseController
  before_action :set_theme, only: [:show, :edit, :update, :destroy, :add_page, :create_pages]

  def index
    @themes = Theme.all
  end

  def show
    @theme = Theme.find(params[:id])

    unless @theme.pages.nil?
      @themePages = @theme.pages.first[1]
    else
      @themePages = @theme.pages
    end
  end

  def theme_css
    @theme = Theme.find(params[:id])

  end

  def theme_css_save
    @theme = Theme.find(params[:id])
    css_conent = params[:css]
    @theme.global_css = css_conent

    if @theme.save
      redirect_to admin_theme_css_path(@theme), notice: 'CSS Saved'
    else
      redirect_to admin_theme_css_path(@theme), notice: 'CSS Not Saved'
    end
  end

  def add_page
    @theme = Theme.find(params[:id])

    if @theme.website_count(@theme) >= 1
      redirect_to admin_theme_path(@theme), alert: 'You cant edit a theme with websites attached'
    end

    # Get existing pages to display in the form
    @existing_pages = []
    if @theme.pages && @theme.pages["theme_pages"]
      @theme.pages["theme_pages"].each do |page_name, page_data|
        @existing_pages << {
          "page_name" => page_name.titleize,
          "page_slug" => page_data["slug"],
          "package_type" => page_data["package_type"],
          "theme_page_id" => page_data["theme_page_id"],
          "position" => page_data["position"]
        }
      end
    end

    # Initialize with one empty page structure for new pages
    @new_pages = [{ "page_name" => "", "page_slug" => "", "package_type" => "" }]
  end

  def create_pages
    @theme = Theme.find(params[:id])

    # Get existing pages structure or initialize
    existing_data = @theme.pages || {}
    existing_theme_pages = existing_data["theme_pages"] || {}

    # Calculate the next position
    next_position = existing_theme_pages.length + 1

    # Process new pages from form
    new_pages_data = pages_params
    success_count = 0
    @errors = []

    new_pages_data.each_with_index do |page_data, index|
      # Validate required fields
      if page_data["page_slug"].blank? || page_data["page_name"].blank? || page_data["package_type"].blank?
        @errors << "Page #{index + 1}: All fields are required"
        next
      end

      # Check if slug already exists in current theme
      if existing_theme_pages.values.any? { |page| page["slug"] == page_data["page_slug"] }
        @errors << "Page #{index + 1}: Slug '#{page_data["page_slug"]}' already exists in this theme"
        next
      end

      # Check if page name already exists in current theme
      if existing_theme_pages.key?(page_data["page_name"].downcase)
        @errors << "Page #{index + 1}: Page name '#{page_data["page_name"]}' already exists in this theme"
        next
      end

      # Add to existing theme_pages with page name as key
      existing_theme_pages[page_data["page_name"].downcase] = {
        "theme_page_id" => SecureRandom.uuid,
        "components" => [],
        "inner_pages_components" => [],
        "inner_pages" => {},
        "slug" => page_data["page_slug"],
        "package_type" => page_data["package_type"],
        "position" => (next_position + index).to_s,
        "seo" => {"focus_keyword" => '',
                  "title_tag" => '',
                  "meta_description" => ''}

      }
      success_count += 1
    end

    if @errors.empty?
      # Update the theme with the new structure
      updated_data = existing_data.merge("theme_pages" => existing_theme_pages)
      @theme.update(pages: updated_data)
      redirect_to admin_theme_path(@theme), notice: "#{success_count} page(s) added successfully!"
    else
      @new_pages = new_pages_data
      flash.now[:alert] = "Some pages couldn't be added. Please check the errors below."
      render :add_page
    end
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)

    if @theme.save
      redirect_to admin_theme_path(@theme), notice: 'Theme was successfully created.'
    else
      # Add this to see what errors are occurring
      puts "Theme errors: #{@theme.errors.full_messages}"
      render :new
    end
  end

  def edit
    @theme = Theme.find(params[:id])

    if @theme.website_count(@theme) >= 1
      redirect_to admin_themes_path, alert: 'You cant edit a theme with websites attached'
    end
  end

  def update
    if @theme.update(theme_params)
      redirect_to admin_theme_path(@theme), notice: 'Theme was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @theme.destroy
    redirect_to admin_themes_path, notice: 'Theme was successfully deleted.'
  end

  def settings
    @theme = Theme.find(params[:id])
  end

  def update_settings
    @theme = Theme.find(params[:id])

    # Get existing settings or initialize empty hash
    current_settings = @theme.settings || {}

    # Merge new settings with existing ones
    new_settings = current_settings.merge(settings_params)

    if @theme.update(settings: new_settings)
      redirect_to admin_themes_settings_path(@theme), notice: 'Theme settings were successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating the theme settings.'
      render :settings
    end
  end

  private

  def set_theme
    @theme = Theme.find(params[:id])
  end

  def theme_params
    params.require(:theme).permit(:name, :description, :image, :pages).tap do |permitted|
      if permitted[:pages].present?
        # Convert comma-separated string to array
        permitted[:pages] = permitted[:pages].split(',').map(&:strip).reject(&:blank?)
      end
    end
  end

  def pages_params
    params.require(:new_pages).values.map do |page_params|
      page_params.permit(:page_name, :page_slug, :package_type)
    end
  end

  def settings_params
    # Updated to properly permit nested parameters
    params.require(:theme).permit(
      settings: {
        "Colour Scheme" => [:primary_colour, :secondary_colour, :primary_hover_colour, :secondary_hover_colour],
        "Font Scheme" => [:title_font, :text_font, :button_font],
        "Background Colour Scheme" => [:background_colour]
      }
    )[:settings]
  end
end

app/helpers/admin/themes_helper.rb
module Admin::ThemesHelper
end

app/views/admin/themes/edit.html.erb
<!-- app/views/admin/themes/edit.html.erb -->
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h2>Edit Theme</h2>
          <%= link_to "View Theme", admin_theme_path(@theme), class: "btn btn-outline-primary" %>
        </div>
        <div class="card-body">
          <%= render 'form', theme: @theme %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/themes/index.html.erb
<!-- app/views/admin/themes/index.html.erb.html.erb -->
<div>
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-3xl font-bold text-gray-900">Themes</h1>
      <p class="mt-2 text-sm text-gray-700">A list of all themes in your application including their name, description, and preview images.</p>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <%= link_to "Add Theme", new_admin_theme_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
    </div>
  </div>

  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Theme</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Websites</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Preview</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Created</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Actions</span>
              </th>
            </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
            <% @themes.each do |theme| %>
              <tr class="hover:bg-gray-50">
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                  <div class="flex items-center">
                    <div class="h-10 w-10 flex-shrink-0">
                      <% if theme.image.attached? %>

                        <%= image_tag theme.image, class: "h-10 w-10 rounded-lg object-cover border border-gray-200" %>
                      <% else %>
                        <div class="card-img-top bg-light d-flex align-items-center justify-content-center" style="height: 200px;">
                          <i class="fas fa-image fa-3x text-muted"></i>
                        </div>
                      <% end %>
                      <div class="h-10 w-10 rounded-lg bg-gray-100 flex items-center justify-center <%= 'hidden' if theme.image.present? %>">
                        <svg class="h-6 w-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                        </svg>
                      </div>
                    </div>
                    <div class="ml-4">
                      <div class="text-sm font-medium text-gray-900"><%= theme.name %></div>
                    </div>
                  </div>
                </td>
                <td class="px-3 py-4 text-sm text-gray-500 max-w-xs">
                  <% if theme.description.present? %>
                    <div class="truncate">
                      <%= truncate(theme.description, length: 60) %>
                    </div>
                  <% else %>
                    <span class="text-gray-400 italic">No description</span>
                  <% end %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <p><%= theme.website_count(theme) %> Websites</p>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <% if theme.image.present? %>
                    <span class="inline-flex rounded-full px-2 text-xs font-semibold leading-5 bg-green-100 text-green-800">
                      Has Image
                    </span>
                  <% else %>
                    <span class="inline-flex rounded-full px-2 text-xs font-semibold leading-5 bg-gray-100 text-gray-800">
                      No Image
                    </span>
                  <% end %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <%= theme.created_at.strftime("%b %d, %Y") %>
                </td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <%= link_to "View", admin_theme_path(theme), class: "text-indigo-600 hover:text-indigo-900 mr-3" %>
                  <% if theme.website_count(theme) >= 1 %>
                    <a class="text-indigo-600 hover:text-indigo-900 mr-3 line-through"> Edit</a>
                <% else %>
                    <%= link_to "Edit", edit_admin_theme_path(theme), class: "text-indigo-600 hover:text-indigo-900 mr-3" %>

                <% end %>
                  <%= link_to "Delete", admin_theme_path(theme), method: :delete,
                              confirm: "Are you sure you want to delete this theme?",
                              class: "text-red-600 hover:text-red-900" %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <% if @themes.empty? %>
    <div class="text-center py-12">
      <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zM21 5a2 2 0 00-2-2h-4a2 2 0 00-2 2v12a4 4 0 004 4h4a2 2 0 002-2V5z" />
      </svg>
      <h3 class="mt-2 text-sm font-medium text-gray-900">No themes</h3>
      <p class="mt-1 text-sm text-gray-500">Get started by creating a new theme.</p>
      <div class="mt-6">
        <%= link_to "Add Theme", admin_themes_new_path, class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/themes/new.html.erb
<!-- app/views/admin/themes/new.html.erb -->
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2>New Theme</h2>
        </div>
        <div class="card-body">
          <%= render 'form', theme: @theme %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/themes/theme_css.html.erb
<div class="min-h-screen space-y-5">
  <div class="bg-white shadow-sm border border-gray-200 overflow-hidden sm:rounded-lg">
    <div class="px-4 py-5 sm:px-6 flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
      <div class="flex-1">
        <h3 class="text-xl leading-6 font-semibold text-gray-900"><%= @theme.name %> - CSS</h3>
        <p class="mt-2 max-w-2xl text-sm text-gray-600"><%= @theme.description %></p>
      </div>
      <div class="flex flex-wrap gap-2 sm:gap-3">
        <%= link_to "Add Page", admin_add_page_path(@theme),
                    class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-lg text-gray-700 bg-white hover:bg-gray-50 hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200" %>
        <%= link_to "Edit Theme", edit_admin_theme_path(@theme),
                    class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-lg text-gray-700 bg-white hover:bg-gray-50 hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200" %>
        <%= link_to "Back To Themes", admin_themes_path,
                    class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-lg text-gray-700 bg-white hover:bg-gray-50 hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200" %>
      </div>
    </div>
  </div>

  <div class="bg-white shadow-sm border border-gray-200 overflow-hidden sm:rounded-lg">
    <div class="px-4 py-5">
      <%= form_with(url: admin_theme_css_save_path(@theme), local: true, class: "") do |form| %>
        <div>
          <%= form.label :css, "CSS Code", class: "block text-sm font-medium text-gray-700 mb-2" %>
          <%= form.text_area :css,
                             value: @theme.global_css,
                             rows: 20,
                             placeholder: "/* Enter your CSS code here */",
                             class: "block w-full px-3 py-2 border border-gray-300 rounded-lg shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 font-mono text-sm resize-y" %>
        </div>

        <div class="flex items-center justify-end space-x-3 mt-6">
          <%= link_to "Cancel", admin_theme_path(@theme),
                      class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-lg text-gray-700 bg-white hover:bg-gray-50 hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200" %>
          <%= form.submit "Save CSS",
                          class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-lg text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200" %>
        </div>
      <% end %>
    </div>
  </div>
</div>